#include <math.h>
#include <string.h>
#include "utils.h"
/// @file
/// Implementation of Project Euler Problem 12
///
/// @addtogroup Problem
/// @{
// -----------------------------------------------------------------------------
/**
  @brief Find the first triangular number with more than n divisors

  @param[in] n            number of divisors
  @param[out] tirangular  triangular number

  @return An error code: 0 - success, otherwise - failure
**/
// -----------------------------------------------------------------------------
int problem012(int n, long *triangular) {
  int maxits = 500000, i = 1;
  long currTriangular = 0;

  // Check triangular numbers
  while (i < maxits) {
    // Update triangular
    currTriangular += i;

    // Count factors
    int factors = 2;
    int bound = floor(sqrt(currTriangular));
    if (2*bound > n) {
      for (int j = 2; j < bound; j++)
        if (!(currTriangular % j))
          factors += 2;
      if (!(currTriangular % bound))
        factors++;
    }

    // Check
    if (factors > n)
      break;

    // Iterate
    i++;
  }

  // Save result
  if (i < maxits)
    *triangular = currTriangular;
  else
    // LCOV_EXCL_START
    return Error(1, "Number of divisors not reached.", NULL);
  // LCOV_EXCL_STOP

  return 0;
};
// -----------------------------------------------------------------------------
/// @}
///
/// @addtogroup Interface
/// @{
// -----------------------------------------------------------------------------
/**
  @brief: Project Euler Problem 12

  The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
    first ten terms would be:

  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

  Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

  We can see that 28 is the first triangle number to have over five divisors.

  What is the value of the first triangle number to have over five hundred
    divisors?
**/
// -----------------------------------------------------------------------------
int problem012CL(FILE *stream) {
  int ierr;

  int n;
  long triangular;

  // Get number adjacent from user
  printf("    This code finds the first triangular number with more than [n]\n"
         "      divisors.\n\n");
  ierr = getValidUserInt("      Enter n: ", stream, 1, INT_MAX, &n);
  ErrChk(ierr);

  // Find lcm
  ierr = problem012(n, &triangular); ErrChk(ierr);

  printf("    The first triangular number with more than %d divisors: %ld\n\n",
         n, triangular);

  return 0;
};
// -----------------------------------------------------------------------------
/// @}
